# Generated by Django 5.1.4 on 2025-01-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_plan_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
